# coding: utf-8

"""
    ComicBagi

    PHP Symfony-based comic hosting catalog full-stack.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from comicbagi_openapi.models.set_link_item_language import SetLinkItemLanguage

class TestSetLinkItemLanguage(unittest.TestCase):
    """SetLinkItemLanguage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SetLinkItemLanguage:
        """Test SetLinkItemLanguage
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SetLinkItemLanguage`
        """
        model = SetLinkItemLanguage()
        if include_optional:
            return SetLinkItemLanguage(
                language_lang = '',
                machine_translate = 56
            )
        else:
            return SetLinkItemLanguage(
        )
        """

    def testSetLinkItemLanguage(self):
        """Test SetLinkItemLanguage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
