# coding: utf-8

"""
    ComicBagi

    PHP Symfony-based comic hosting catalog full-stack.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from comicbagi_openapi.api.website_api import WebsiteApi


class TestWebsiteApi(unittest.TestCase):
    """WebsiteApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WebsiteApi()

    def tearDown(self) -> None:
        pass

    def test_add_website(self) -> None:
        """Test case for add_website

        Add website.
        """
        pass

    def test_add_website_item_language(self) -> None:
        """Test case for add_website_item_language

        Add website item language.
        """
        pass

    def test_delete_website(self) -> None:
        """Test case for delete_website

        Delete website.
        """
        pass

    def test_delete_website_item_language(self) -> None:
        """Test case for delete_website_item_language

        Delete website item language.
        """
        pass

    def test_get_website(self) -> None:
        """Test case for get_website

        Get website.
        """
        pass

    def test_get_website_item_language(self) -> None:
        """Test case for get_website_item_language

        Get website item language.
        """
        pass

    def test_list_website(self) -> None:
        """Test case for list_website

        List website.
        """
        pass

    def test_list_website_item_language(self) -> None:
        """Test case for list_website_item_language

        List website item language.
        """
        pass

    def test_update_website(self) -> None:
        """Test case for update_website

        Update website.
        """
        pass

    def test_update_website_item_language(self) -> None:
        """Test case for update_website_item_language

        Update website item language.
        """
        pass


if __name__ == '__main__':
    unittest.main()
