# coding: utf-8

"""
    ComicBagi

    PHP Symfony-based comic hosting catalog full-stack.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from comicbagi_openapi.api.link_api import LinkApi


class TestLinkApi(unittest.TestCase):
    """LinkApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LinkApi()

    def tearDown(self) -> None:
        pass

    def test_add_link(self) -> None:
        """Test case for add_link

        Add link.
        """
        pass

    def test_add_link_item_language(self) -> None:
        """Test case for add_link_item_language

        Add link item language.
        """
        pass

    def test_delete_link(self) -> None:
        """Test case for delete_link

        Delete link.
        """
        pass

    def test_delete_link_item_language(self) -> None:
        """Test case for delete_link_item_language

        Delete link item language.
        """
        pass

    def test_get_link(self) -> None:
        """Test case for get_link

        Get link.
        """
        pass

    def test_get_link_item_language(self) -> None:
        """Test case for get_link_item_language

        Get link item language.
        """
        pass

    def test_list_link(self) -> None:
        """Test case for list_link

        List link.
        """
        pass

    def test_list_link_item_language(self) -> None:
        """Test case for list_link_item_language

        List link item language.
        """
        pass

    def test_update_link(self) -> None:
        """Test case for update_link

        Update link.
        """
        pass

    def test_update_link_item_language(self) -> None:
        """Test case for update_link_item_language

        Update link item language.
        """
        pass


if __name__ == '__main__':
    unittest.main()
