# coding: utf-8

"""
    ComicBagi

    PHP Symfony-based comic hosting catalog full-stack.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from comicbagi_openapi.api.comic_api import ComicApi


class TestComicApi(unittest.TestCase):
    """ComicApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ComicApi()

    def tearDown(self) -> None:
        pass

    def test_add_comic(self) -> None:
        """Test case for add_comic

        Add comic.
        """
        pass

    def test_add_comic_destination_link(self) -> None:
        """Test case for add_comic_destination_link

        Add comic destination link.
        """
        pass

    def test_delete_comic(self) -> None:
        """Test case for delete_comic

        Delete comic.
        """
        pass

    def test_delete_comic_destination_link(self) -> None:
        """Test case for delete_comic_destination_link

        Delete comic destination link.
        """
        pass

    def test_get_comic(self) -> None:
        """Test case for get_comic

        Get comic.
        """
        pass

    def test_get_comic_destination_link(self) -> None:
        """Test case for get_comic_destination_link

        Get comic destination link.
        """
        pass

    def test_list_comic(self) -> None:
        """Test case for list_comic

        List comic.
        """
        pass

    def test_list_comic_destination_link(self) -> None:
        """Test case for list_comic_destination_link

        List comic destination link.
        """
        pass

    def test_update_comic(self) -> None:
        """Test case for update_comic

        Update comic.
        """
        pass

    def test_update_comic_destination_link(self) -> None:
        """Test case for update_comic_destination_link

        Update comic destination link.
        """
        pass


if __name__ == '__main__':
    unittest.main()
