# coding: utf-8

"""
    ComicBagi

    PHP Symfony-based comic hosting catalog full-stack.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from comicbagi_openapi.api.comic_chapter_api import ComicChapterApi


class TestComicChapterApi(unittest.TestCase):
    """ComicChapterApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ComicChapterApi()

    def tearDown(self) -> None:
        pass

    def test_add_comic_chapter(self) -> None:
        """Test case for add_comic_chapter

        Add comic chapter.
        """
        pass

    def test_add_comic_chapter_destination_link(self) -> None:
        """Test case for add_comic_chapter_destination_link

        Add comic chapter destination link.
        """
        pass

    def test_delete_comic_chapter(self) -> None:
        """Test case for delete_comic_chapter

        Delete comic chapter.
        """
        pass

    def test_delete_comic_chapter_destination_link(self) -> None:
        """Test case for delete_comic_chapter_destination_link

        Delete comic chapter destination link.
        """
        pass

    def test_get_comic_chapter(self) -> None:
        """Test case for get_comic_chapter

        Get comic chapter.
        """
        pass

    def test_get_comic_chapter_destination_link(self) -> None:
        """Test case for get_comic_chapter_destination_link

        Get comic chapter destination link.
        """
        pass

    def test_list_comic_chapter(self) -> None:
        """Test case for list_comic_chapter

        List comic chapter.
        """
        pass

    def test_list_comic_chapter_destination_link(self) -> None:
        """Test case for list_comic_chapter_destination_link

        List comic chapter destination link.
        """
        pass

    def test_update_comic_chapter(self) -> None:
        """Test case for update_comic_chapter

        Update comic chapter.
        """
        pass

    def test_update_comic_chapter_destination_link(self) -> None:
        """Test case for update_comic_chapter_destination_link

        Update comic chapter destination link.
        """
        pass


if __name__ == '__main__':
    unittest.main()
