# coding: utf-8

"""
    ComicBagi

    PHP Symfony-based comic hosting catalog full-stack.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from comicbagi_openapi.models.new_website_item_language import NewWebsiteItemLanguage

class TestNewWebsiteItemLanguage(unittest.TestCase):
    """NewWebsiteItemLanguage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NewWebsiteItemLanguage:
        """Test NewWebsiteItemLanguage
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NewWebsiteItemLanguage`
        """
        model = NewWebsiteItemLanguage()
        if include_optional:
            return NewWebsiteItemLanguage(
                language_lang = '',
                machine_translate = 56
            )
        else:
            return NewWebsiteItemLanguage(
                language_lang = '',
        )
        """

    def testNewWebsiteItemLanguage(self):
        """Test NewWebsiteItemLanguage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
